Flip card animation
filwas/fischkapp pull request #12
Opened 2023-07-16 15:11 UTC by filwas

2023-07-16 15:23 UTC, filwas commented on src/components/Card.module.css
> +  }
I'm really fond of this "hack". Initially I was rotating by 180 degrees, which caused everything to be a mirror-image, and the text was changing too soon. So, I added a timeout that makes the text change happen exactly in the middle - when the card is just a straight line - and made the animation only turn by 90 degrees, just to make it go back. Visually it tricks the mind that a flip is happening, but in reality it was really simple to implement.

This task reminded me of the mouse cursor animation during loading in the old game Battlefield 2. I cannot find a video link, but it was basically the same trick as the one I used here.

2023-07-16 15:26 UTC, filwas commented on src/components/Card.tsx
> +  ].join(" ")
I couldn't find it in the design, but initially I was thinking of making two animations - right flip and left flip - which would play depending on which side was displayed initially. If you think I should add it, I will.

2023-07-17 11:43 UTC, Sumick requested changes
Rejecting, as you have a lot of things to fix from previous PRs

2023-07-19 14:18 UTC, Sumick requested changes
There is a lot of old stuff here - let's finish that first PR, merge main into it so it's clear what is happening in terms of this specific task requirements

2023-07-19 16:10 UTC, Sumick approved these changes

2023-07-19 16:59 UTC, merged