Implement get flashcards
filwas/fischkapp pull request #13
Opened 2023-07-21 16:22 UTC by filwas

2023-07-22 15:19 UTC, Sumick requested changes
Mostly looks good, however we need few improvements - please repeat this pattern into other PRs. Or finish that one, and then merge it into others

2023-07-22 15:19 UTC, Sumick commented on src/App.tsx
> +    importCards().then((importedCardsArray) => {
**nitpick:** Let's name it more meaningful - like `fetchCards`, `getCards` or something similar. Import is rather reserved keyword for importing code parts across the codebase

2023-07-22 15:19 UTC, Sumick commented on src/apiService.ts
> +): Promise<T> => {
**nitpick:** url is unused. Let's do:

```js
const BASE_URL = "https://training.nerdbord.io/api/v1/fischkapp"

export const customFetch = async <T>(
  url: string,
  options: RequestInit = {}
): Promise<T> => {
  try {
    const response = await fetch(
      BASE_URL + url,
      options
    );
```

2023-07-22 15:19 UTC, Sumick commented on src/apiService.ts
> +    const data = await customFetch<ImportedCardObject[]>("");
**nitpick:** Then do:

```js
const data = await customFetch<ImportedCardObject[]>("/flashcards");
```

2023-07-23 11:53 UTC, filwas commented on src/App.tsx
> +    fetchCards()
changed function name as pre nitpick

2023-07-23 12:00 UTC, filwas commented on src/App.tsx
> +            key={card.id}
This change actually fixed a bug I had, which caused a situation where after deleting a card, the next card suddenly "inherited" the height of the deleted card. I guess this is a good example that shows how react renders and distinguishes between elements, and why keys should be unique not only to their "peers".

2023-07-23 15:19 UTC, Sumick requested changes
Looks good! I found one naming issue + we should have only changes related to task requirements here. Now you mixed everything - we should fix it. 

TODO:

- [x] This PR should have only task related changes.

2023-07-23 15:19 UTC, Sumick commented on src/App.tsx
> +    await exportCard(card);
**nitpick:** `Export`, is the same like `import` - it's registered keyword for doing very specific thing. We should not name `post` functions with it. Let's change it to `postNewCard` or something similar

2023-07-24 09:08 UTC, Sumick approved these changes
Great job!

2023-07-24 12:19 UTC, merged