App header
filwas/fischkapp pull request #2
Opened 2023-07-07 16:59 UTC by filwas

2023-07-07 17:30 UTC, Sumick requested changes
We need few improvements here

2023-07-07 17:30 UTC, Sumick commented on src/components/AppHeader.tsx
> +  cardsAmt: Number;
**nitpick:** Let's add more descriptive prop names instead of shortening it this way, eg: (`cardsAmount`)

2023-07-07 17:30 UTC, Sumick commented on src/components/AppHeader.tsx
> +        Cards amount: {props.cardsAmt.toString()}
**nitpick:** You don't have to do this (`toString`)

2023-07-07 17:30 UTC, Sumick commented on src/components/AppHeader.tsx
> +      <AddNewButton />
**nitpick:** Why this button is nested in button? AddNewButton should contain `button`, and SVG icon together, as one component

2023-07-07 17:30 UTC, Sumick commented on public/fischLogo.tsx
> +const FischLogo = () => {
**nitpick:** Components file names should be written with `PascalCase`

2023-07-07 17:30 UTC, Sumick commented on public/fischLogo.tsx
> +    <svg
**issue:** React components should not be placed in `public` directory. Keep it in `components` like any other component. If you want to keep SVG asset in `public` you should keep it in `.svg` file extension

2023-07-08 12:07 UTC, filwas commented
Comments applied. Please take a look at AppHeader.tsx line 15, because I had a problem there. When I was simply passing props.cardAmount, I got an error `Type 'Number' is not assignable to type 'ReactNode'. `. To get rid of the error, I used .toString() method, but you said I shouldn't have to use it. After a while, I realised the error I'm getting doesn't affect anything and even though the variable has a red underscore in my IDE, the element renders correctly with the provided number. 

In the end, I used this temporary fix to get rid of the underline: https://www.youtube.com/watch?v=AEQij4AnjYU

2023-07-08 13:43 UTC, Sumick approved these changes
Looks good!

2023-07-08 14:08 UTC, merged